### ISSUE TITLE
Delete post endpoint

### ISSUE THREAD

**Issue by AnindaS13** [Project-Chirp/chirp-backend#52]
The API endpoint for deleting a post. The endpoint should be a DELETE endpoint and hard delete the post from the database. Checks should be in place to make sure that only the owner of the post can delete it

**Comment by NasihNazeem** [comment]
### Proposal for #52. 

A soft delete for posts where we toggle an active boolean for deletion of posts. This will void the requirement for a parentPostId to exist for all replies, and the likes can still be deleted. It will also help with further development if we want to give users access to see the parent post of any reply instead of just seeing a random reply when you expand it with no context of what they were replying to. 

## Further Explanation

A hard delete from the post table has a few ramifications that I can think of with the way we currently hold data. All replies right now are queried for when parentPostId != NULL. We cannot delete the parentPost without deleting the replies since that will be a violation of fk constraint. We would have to make the parentPostId NULL. However, we are already querying for the fact that if a parentPostId is NULL, then that means that post itself is a root post.

So if we were to make a parentPostId NULL for replies, that would be those replies are now parent posts themselves, when that shouldn't be the case.

We can still delete likes from the liked_post table since we do not have a need for them anymore after a delete.

**Comment by Dennull** [comment]
This is a good point @NasihNazeem. We'd have to think about if we want to delete cascade or update cascade, stuff like that. It also brings up the question, what should we do with replies that are replying to a deleted post? We can just delete them along with the post, or we can also delete the original post but keep the reply. I think Twitter itself does this and I know Reddit does the same thing.

I think it makes sense to go with the soft delete for now until we decide what we want to do moving forward. We also talked about changing the database schema for our repost feature anyways, so a soft delete would let us merge this feature without a big headache until we do the database changes
